{
 "title": "Trader Bot",
 "time": { "from": "2018-04-12T02:12:03.302Z", "to": "2018-04-12T14:12:26.951Z" },
 "panels": [
  {
   "title": "Price History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "measurement": "stream",
     "query": "SELECT \"volume\" FROM \"stream\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Volume",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "query": "SELECT max(\"volume\") FROM \"stream\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "stream",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "Trader  Bot Settings",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "content": "<form action=\"/bot/change\" method=\"post\">\n  <div class=\"gf-form\">\n    <label for=\"algorithm-picker\" class=\"gf-form-label width-10\">Exchange</label>\n    <div class=\"gf-form-select-wrapper max-width-20\">\n      <select name=\"algorithm\" id=\"algorithm-picker\" class=\"input-large gf-form-input\">\n        <option selected disabled>Choose an exchange to use</option>\n        <option value=\"poloniex\">Livecoin</option> \n        <option value=\"poloniex\" disabled>Poloniex</option>\n        <option value=\"poloniex\" disabled>GDAX</option>\n      </select>\n    </div>\n  </div>\n  <div class=\"gf-form\">\n    <label for=\"algorithm-picker\" class=\"gf-form-label width-10\">Strategy</label>\n    <div class=\"gf-form-select-wrapper max-width-20\">\n      <select name=\"algorithm\" id=\"algorithm-picker\" class=\"input-large gf-form-input\">\n        <option selected disabled>Choose strategy to use</option>\n        <option value=\"pp\">Pingpong</option>\n        <option value=\"uptrend\">Uptrend</option>\n        <option value=\"bb\">Bollinger Bands</option>\n        <option value=\"bbgain\">Bollinger Bands - Gain</option>\n        <option value=\"bbpp\">Bollinger Bands - Pingpong</option>\n        <option value=\"bbrsitssl\">Bollinger Bands &#43; RSI - Trailing Stop / Stop Limit</option>\n        <option value=\"bbstepgain\">Bollinger Bands - Stepgain</option>\n        <option value=\"bbtssl\">Bollinger Bands - Trailing Stop / Stop Limit</option>\n        <option value=\"emotionless\">Emotionless</option>\n        <option value=\"gain\">Gain</option>\n        <option value=\"gainbb\">Gain - Bollinger Bands</option>\n        <option value=\"gainpp\">Gain - Pingpong</option>\n        <option value=\"gainstepgain\">Gain - Stepgain</option>\n        <option value=\"gaintssl\">Gain - Trailing Stop / Stop Limit</option>\n        <option value=\"ichimoku\">Ichimoku</option>\n        <option value=\"ppbb\">Pingpong - Bollinger Bands</option>\n        <option value=\"ppstepgain\">Pingpong - Stepgain</option>\n        <option value=\"pptssl\">Pingpong - Trailing Stop / Stop Limit</option>\n        <option value=\"stepgain\">Stepgain</option>\n        <option value=\"stepgainbb\">Stepgain - Bollinger Bands</option>\n        <option value=\"stepgaingain\">Stepgain - Gain</option>\n        <option value=\"stepgainpp\">Stepgain - Pingpong</option>\n        <option value=\"stepgaintssl\">Stepgain - Trailing Stop / Stop Limit</option>\n        <option value=\"tssl\">Trailing Stop / Stop Limit</option>\n        <option value=\"tsslbb\">Trailing Stop / Stop Limit - Bollinger Bands</option>\n        <option value=\"tsslgain\">Trailing Stop / Stop Limit - Gain</option>\n        <option value=\"tsslpp\">Trailing Stop / Stop Limit - Pingpong</option>\n        <option value=\"tsslstepgain\">Trailing Stop / Stop Limit - Stepgain</option>\n      </select>\n    </div>\n  </div>\n  <button class=\"btn btn-success width-10\" type=\"submit\">Change Settings</button>\n</form>"
  },
  {
   "title": "Portfolio",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 16 },
   "content": "<form>\n  <div>\n    ETH\n  </div>\n  <div>\n    BTC\n  </div>\n</form>"
  },
  { "title": "Currencies Enabled", "type": "text", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 }, "content": "# BTC / USD" },
  {
   "title": "Bot Trade Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "stream",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bitcoin Wallet Transaction",
   "type": "table",
   "description": "Provides wallet transaction detail for your bitcoin account.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}