{
 "title": "Trader Bot",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  {
   "title": "BTC / USD - Price History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Market Price" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "description": "Volume base on LiveCoin ticker.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Trade Volume" }
   ],
   "targets": [
    {
     "alias": "volume",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=", "value": "btc_usd" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "livecoin" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ticker" }
     ]
    }
   ]
  },
  {
   "title": "Trader  Bot Settings",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "content": "<script type=\"text/javascript\">\n  $(document).ready(() => {\n    $(\"form#setupp\").submit(function(event) {\n      event.preventDefault()\n      var exchange = $(\"#ep\").val()\n      var strategy = $(\"#sp\").val()\n\n      console.log(\"saving settings in backend...\")\n      $.ajax({\n        type: \"POST\",\n        url: \"http://ec2-54-169-102-171.ap-southeast-1.compute.amazonaws.com:8000/bot/setup\",\n        data: \"x=\" + exchange + \"&s=\" + strategy,\n        success: function(){\n          console.log('saved.')\n        }\n      })\n    })\n  })\n</script>\n<br/>\n<form id=\"setupp\" method=\"post\">\n  <div class=\"gf-form\">\n    <label for=\"ep\" class=\"gf-form-label width-10\">Exchange</label>\n    <div class=\"gf-form-select-wrapper max-width-20\">\n      <select name=\"exchange\" id=\"ep\" class=\"input-large gf-form-input\">\n        <option disabled>Choose an exchange to use</option>\n        <option selected value=\"livecoin\">Livecoin</option> \n        <option value=\"poloniex\" disabled>Poloniex</option>\n        <option value=\"gdax\" disabled>GDAX</option>\n      </select>\n    </div>\n  </div>\n  <div class=\"gf-form\">\n    <label for=\"sp\" class=\"gf-form-label width-10\">Buy / Sell Strategy</label>\n    <div class=\"gf-form-select-wrapper max-width-20\">\n      <select name=\"strategy\" id=\"sp\" class=\"input-large gf-form-input\">\n        <option disabled>Choose strategy to use</option>\n        <option selected value=\"pp\">Pingpong</option>\n        <option value=\"uptrend\">Uptrend</option>\n        <option value=\"wavetrend\">Wavetrend</option>\n        <option value=\"bb\" disabled>Bollinger Bands</option>\n        <option value=\"bbgain\" disabled>Bollinger Bands - Gain</option>\n        <option value=\"bbpp\" disabled>Bollinger Bands - Pingpong</option>\n        <option value=\"bbrsitssl\" disabled>Bollinger Bands &#43; RSI - Trailing Stop / Stop Limit</option>\n        <option value=\"bbstepgain\" disabled>Bollinger Bands - Stepgain</option>\n        <option value=\"bbtssl\" disabled>Bollinger Bands - Trailing Stop / Stop Limit</option>\n        <option value=\"emotionless\" disabled>Emotionless</option>\n        <option value=\"gain\" disabled>Gain</option>\n        <option value=\"gainbb\" disabled>Gain - Bollinger Bands</option>\n        <option value=\"gainpp\" disabled>Gain - Pingpong</option>\n        <option value=\"gainstepgain\" disabled>Gain - Stepgain</option>\n        <option value=\"gaintssl\" disabled>Gain - Trailing Stop / Stop Limit</option>\n        <option value=\"ichimoku\" disabled>Ichimoku</option>\n        <option value=\"ppbb\" disabled>Pingpong - Bollinger Bands</option>\n        <option value=\"ppstepgain\" disabled>Pingpong - Stepgain</option>\n        <option value=\"pptssl\" disabled>Pingpong - Trailing Stop / Stop Limit</option>\n        <option value=\"stepgain\" disabled>Stepgain</option>\n        <option value=\"stepgainbb\" disabled>Stepgain - Bollinger Bands</option>\n        <option value=\"stepgaingain\" disabled>Stepgain - Gain</option>\n        <option value=\"stepgainpp\" disabled>Stepgain - Pingpong</option>\n        <option value=\"stepgaintssl\" disabled>Stepgain - Trailing Stop / Stop Limit</option>\n        <option value=\"tssl\" disabled>Trailing Stop / Stop Limit</option>\n        <option value=\"tsslbb\" disabled>Trailing Stop / Stop Limit - Bollinger Bands</option>\n        <option value=\"tsslgain\" disabled>Trailing Stop / Stop Limit - Gain</option>\n        <option value=\"tsslpp\" disabled>Trailing Stop / Stop Limit - Pingpong</option>\n        <option value=\"tsslstepgain\" disabled>Trailing Stop / Stop Limit - Stepgain</option>\n      </select>\n    </div>\n  </div>\n  <br/>\n  <button class=\"btn btn-success width-10\" type=\"submit\">Change Settings</button>\n</form>"
  },
  {
   "title": "Portfolio",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 14 },
   "content": "<div id=\"portfolioPanel\" class=\"ng-scope\">\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#portfoliop\").submit(function(event) {\n        event.preventDefault()\n        var btc = $(\"#pbtc\").val()\n        var key = $(\"#papk\").val()\n        var secret = $(\"#paps\").val()\n  \n        console.log(\"saving portfolio settings in backend...\")\n        $.ajax({\n          type: \"POST\",\n          url: \"http://ec2-54-169-102-171.ap-southeast-1.compute.amazonaws.com:8000/bot/setup/portfolio\",\n          data: \"btc=\" + btc + \"&key=\" + key + \"&secret=\" + secret,\n          success: function(){\n            console.log('saved.')\n          }\n        })\n      })\n    })\n  </script>\n  <form id=\"portfoliop\" method=\"post\">\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-10\">BTC Wallet Address</span>\n      <input id=\"tbp\" type=\"text\" class=\"gf-form-input width-20\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-10\">API Key</span>\n      <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-10\">API Secret</span>\n      <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n    </div>\n    <br/>\n    <button class=\"btn btn-success width-10\" type=\"submit\">Add Account</button>\n  </form>\n  <br/>\n  <button class=\"btn btn-success\">Run Simulation</button>\n  <button class=\"btn btn-success\">Backfill</button>\n  <button class=\"btn btn-warning\">Stop Bot Transactions</button>\n</div>"
  },
  {
   "title": "Bitcoin Wallet Balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bitcoin Price",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "format": "currencyUSD",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "livecoin" },
      { "condition": "AND", "key": "pair", "operator": "=", "value": "btc_usd" }
     ]
    }
   ]
  },
  {
   "title": "Ping Pong",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "content": "<script type=\"text/javascript\">\n  $(document).ready(() => {\n    $(\"form#tradep\").submit(function(event) {\n      event.preventDefault()\n      var buy = $(\"#tbp\").val()\n      var sell = $(\"#tsp\").val()\n\n      console.log(\"saving trade settings in backend...\")\n      $.ajax({\n        type: \"POST\",\n        url: \"http://ec2-54-169-102-171.ap-southeast-1.compute.amazonaws.com:8000/bot/setup/pp\",\n        data: \"bp=\" + buy + \"&sp=\" + sell,\n        success: function(){\n          console.log('saved.')\n        }\n      })\n    })\n  })\n</script>\n<br/>\n<form id=\"tradep\" method=\"post\">\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-10\">Buy Price</span>\n    <input id=\"tbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-10\">Sell Price</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <br/>\n  <button class=\"btn btn-success width-10\" type=\"submit\">Change Settings</button>\n</form>"
  },
  {
   "title": "Bot Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Currency Pair", "type": "text", "gridPos": { "h": 4, "w": 5, "x": 8, "y": 21 }, "content": "# BTC / USD" },
  {
   "title": "Rules",
   "type": "text",
   "description": "Rule 1 - No other in queue\nRule 2 - Someone blocking",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 21 }
  },
  {
   "title": "Other Bot Configurations",
   "type": "text",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "content": "<script type=\"text/javascript\">\n  $(document).ready(() => {\n    $(\"form#tradep\").submit(function(event) {\n      event.preventDefault()\n      var buy = $(\"#tbp\").val()\n      var sell = $(\"#tsp\").val()\n\n      console.log(\"saving trade settings in backend...\")\n      $.ajax({\n        type: \"POST\",\n        url: \"http://ec2-54-169-102-171.ap-southeast-1.compute.amazonaws.com:8000/bot/setup/pp\",\n        data: \"bp=\" + buy + \"&sp=\" + sell,\n        success: function(){\n          console.log('saved.')\n        }\n      })\n    })\n  })\n</script>\n<br/>\n<form id=\"otherbot\" method=\"post\">\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Maximum Volume</span>\n    <input id=\"tbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Transaction Volume (per Deal)</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Variance of Transaction Volume</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Bid Price Step Down Amount</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Minimum Bid Price</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <div class=\"gf-form\">\n    <span class=\"gf-form-label width-20\">Accounts</span>\n    <input id=\"sbp\" type=\"text\" class=\"gf-form-input width-20\">\n  </div>\n  <br/>\n  <button class=\"btn btn-success width-10\" type=\"submit\">Change Settings</button>\n</form>"
  },
  {
   "title": "Account List",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT * from accounts;"
    }
   ]
  },
  {
   "title": "Trader Bot Action Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "measurement": "transactions",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}