{
 "title": "Trader Bot",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "7s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server Type",
    "query": "localhost, trade-bot.smartfunding.io"
   },
   { "name": "protocol", "label": "Protocol", "query": "https,http" }
  ]
 },
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NOX / ETH - Price History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Market Price" }
   ],
   "targets": [
    {
     "alias": "Price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Sell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Buy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NOX / ETH - Volume",
   "type": "graph",
   "description": "Volume base on LiveCoin ticker.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Trade Volume" }
   ],
   "targets": [
    {
     "alias": "volume",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "volume" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "livecoin" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ticker" }
     ]
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Portfolio Account One",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "content": "<div id=\"accountsPanel\" class=\"ng-scope\">\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#accountOne\").submit(function(event) {\n        event.preventDefault()\n        console.log(\"saving portfolio settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/accounts\"\n        $.ajax({\n          dataType: \"json\",\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#accountOne\").serialize(),\n          success: function(data) {\n            console.log(data)\n            $('#accountOnePassword').val('')\n            if (data.success == true) {\n              alert('Account one saved!')\n              console.log('saved.')\n            } else {\n              alert('Account one not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <section>\n    <form id=\"accountOne\" method=\"post\">\n      <input type=\"hidden\" name=\"id\" value=\"1\">\n      <div class=\"gf-form\">\n        <span class=\"gf-form-label width-20\">API Key</span>\n        <input name=\"key\" type=\"text\" class=\"gf-form-input width-20\" placeholder=\"API Key\">\n      </div>\n      <div class=\"gf-form\">\n        <span class=\"gf-form-label width-20\">API Secret</span>\n        <input name=\"secret\" id=\"accountOnePassword\" type=\"password\" class=\"gf-form-input width-20\" placeholder=\"API Secret\">\n      </div>\n      <br/>\n      <button class=\"btn btn-success width-20\" type=\"submit\">Change Account One</button>\n    </form>\n  </section>\n  <br/>\n</div>"
  },
  {
   "title": "Portfolio Account Two",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "content": "<div id=\"accountsPanel\" class=\"ng-scope\">\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#accountTwo\").submit(function(event) {\n        event.preventDefault()\n        console.log(\"saving portfolio settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/accounts\"\n        $.ajax({\n          dataType: \"json\",\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#accountTwo\").serialize(),\n          success: function(data) {\n            console.log(data)\n            $('#accountTwoPassword').val('')\n            if (data.success == true) {\n              alert('Account two saved!')\n              console.log('saved.')\n            } else {\n              alert('Account two not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <section>\n    <form id=\"accountTwo\" method=\"post\">\n      <input type=\"hidden\" name=\"id\" value=\"2\">\n      <div class=\"gf-form\">\n        <span class=\"gf-form-label width-20\">API Key</span>\n        <input name=\"key\" type=\"text\" class=\"gf-form-input width-20\" placeholder=\"API Key\">\n      </div>\n      <div class=\"gf-form\">\n        <span class=\"gf-form-label width-20\">API Secret</span>\n        <input name=\"secret\" id=\"accountTwoPassword\" type=\"password\" class=\"gf-form-input width-20\" placeholder=\"API Secret\">\n      </div>\n      <br/>\n      <button class=\"btn btn-success width-20\" type=\"submit\">Change Account Two</button>\n    </form>\n  </section>\n  <br/>\n</div>"
  },
  {
   "title": "Rule One Configuration",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "content": "<section>\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#ruleOneConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/settings\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#ruleOneConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Rule one configuration saved!')\n              console.log('saved.')\n            } else {\n              alert('Rule one configuration not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <form id=\"ruleOneConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"id\" value=\"1\">\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Interval (e.g. 1s is 1 second)</span>\n      <input name=\"interval\" type=\"text\" class=\"gf-form-input width-20\" value=\"7s\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Maximum Volume</span>\n      <input name=\"maximumVolume\" type=\"text\" class=\"gf-form-input width-20\" value=\"500000\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Transaction Volume (Per Deal)</span>\n      <input name=\"transactionVolume\" type=\"text\" class=\"gf-form-input width-20\" value=\"300\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Variance of Transaction Volume (Percentage)</span>\n      <input name=\"variance\" type=\"text\" class=\"gf-form-input width-20\" value=\"10.0\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Bid Price Step Down Amount</span>\n      <input name=\"stepDownPrice\" type=\"text\" class=\"gf-form-input width-20\" value=\"0.00000001\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Minimum Bid Price</span>\n      <input name=\"minimumBid\" type=\"text\" class=\"gf-form-input width-20\" value=\"0.00011500\">\n    </div>\n    <br/>\n    <button class=\"btn btn-success width-20\" type=\"submit\">Change Settings</button>\n  </form>\n</section>"
  },
  {
   "title": "Rule Two Configuration",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "content": "<section>\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#ruleTwoConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/settings\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#ruleTwoConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Rule two configuration saved!')\n              console.log('saved.')\n            } else {\n              alert('Rule two configuration not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <form id=\"ruleTwoConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"id\" value=\"2\">\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Interval (e.g. 1s is 1 second)</span>\n      <input name=\"interval\" type=\"text\" class=\"gf-form-input width-20\" value=\"7s\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Maximum Volume</span>\n      <input name=\"maximumVolume\" type=\"text\" class=\"gf-form-input width-20\" value=\"500000\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Transaction Volume (Per Deal)</span>\n      <input name=\"transactionVolume\" type=\"text\" class=\"gf-form-input width-20\" value=\"300\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Variance of Transaction Volume (Percentage)</span>\n      <input name=\"variance\" type=\"text\" class=\"gf-form-input width-20\" value=\"10.0\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Bid Price Step Down Amount</span>\n      <input name=\"stepDownPrice\" type=\"text\" class=\"gf-form-input width-20\" value=\"0.00000001\">\n    </div>\n    <div class=\"gf-form\">\n      <span class=\"gf-form-label width-20\">Minimum Bid Price</span>\n      <input name=\"minimumBid\" type=\"text\" class=\"gf-form-input width-20\" value=\"0.00011500\">\n    </div>\n    <br/>\n    <button class=\"btn btn-success width-20\" type=\"submit\">Change Settings</button>\n  </form>\n</section>"
  },
  {
   "title": "Bot Control",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "content": "<section>\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#botPowerOneConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/controls\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#botPowerOneConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Bot power config saved!')\n              console.log('saved.')\n            } else {\n              alert('Bot power config not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n      $(\"form#botPowerTwoConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/controls\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#botPowerTwoConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Bot power config saved!')\n              console.log('saved.')\n            } else {\n              alert('Bot power config not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <form id=\"botPowerOneConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"power\" value=\"1\">\n    <button class=\"btn btn-success width-20\" type=\"submit\">On</button>\n  </form>\n  <br/>\n  <form id=\"botPowerTwoConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"power\" value=\"0\">\n    <button class=\"btn btn-warning width-20\" type=\"submit\">Off</button>\n  </form>\n</section>"
  },
  {
   "title": "Bot Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "bot",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "set", "operator": "=", "value": "bot" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" }
     ]
    }
   ]
  },
  {
   "title": "Bot Simulate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "bot",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "set", "operator": "=", "value": "bot" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "simulate" }
     ]
    }
   ]
  },
  {
   "title": "Bot Simulate Control",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "content": "<section>\n  <script type=\"text/javascript\">\n    $(document).ready(() => {\n      $(\"form#botSimulateOneConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/simulate\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#botSimulateOneConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Bot simulate config saved!')\n              console.log('saved.')\n            } else {\n              alert('Bot simulate config not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n      $(\"form#botSimulateTwoConfiguration\").submit(function(event) {\n        event.preventDefault()\n  \n        console.log(\"saving trade settings in backend...\")\n        var baseurl = \"[[protocol]]://[[server]]:8000/bot/simulate\"\n        $.ajax({\n          type: \"POST\",\n          url: baseurl,\n          data: $(\"form#botSimulateTwoConfiguration\").serialize(),\n          success: function(data) {\n            console.log(data)\n            if (data.success == true) {\n              alert('Bot simulate config saved!')\n              console.log('saved.')\n            } else {\n              alert('Bot simulate config not saved.')\n              console.log('not saved.')\n            }\n          }\n        })\n      })\n    })\n  </script>\n  <br/>\n  <form id=\"botSimulateOneConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"power\" value=\"1\">\n    <button class=\"btn btn-success width-20\" type=\"submit\">On</button>\n  </form>\n  <br/>\n  <form id=\"botSimulateTwoConfiguration\" method=\"post\">\n    <input type=\"hidden\" name=\"power\" value=\"0\">\n    <button class=\"btn btn-warning width-20\" type=\"submit\">Off</button>\n  </form>\n</section>"
  },
  {
   "title": "Bot Export",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "content": "<section>\n  <br/>\n  <form action=\"http://[[server]]:8000/bot/exported\" method=\"get\">\n    <button class=\"btn btn-success width-20\" type=\"submit\">Export CSV File</button>\n  </form>\n  <br/>\n</section>"
  },
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Trader Bot Action Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "measurement": "transactions",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}